services:
    Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigExtension:
        tags:
            - { name: twig.extension }

    Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigRuntime:
        public: false
        tags:
            - { name: twig.runtime }
