services:
    oneup_contao_sentry.twig.extension:
        class: Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigExtension
        tags:
            - { name: twig.extension }

    oneup_contao_sentry.twig.runtime:
        class: Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigRuntime
        public: false
        tags:
            - { name: twig.runtime }

    oneup_contao_sentry.integration.ignore_previous_exceptions:
        class: Oneup\ContaoSentryBundle\Integration\IgnorePreviousExceptionsIntegration
